# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- .jekyll-cache
- .gitignore
- .DS_Store

# 2. Installed Gems
plugins:
# - jekyll-sitemap
- jekyll-paginate-v2
#- jekyll-seo-tag
#- jekyll-redirect-from
#- jekyll-default-layout
#- jekyll-feed
#- jekyll-commonmark
#- jekyll-include-cache
#- jemoji

# 3. Gem settings
pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: 110101lab # jekyll-seo-tag > Owners twitter username
author: Malte K # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Malte K # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/110101lab
    - https://github.com/110101
markdown: kramdown # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike
highlighter: rouge

# 5. Collections
collections:
  posts:
    title: Human-Ready Future # Needed for Siteleaf
    description: "My thoughts and ideas"
    output: true
    feature_text: |
      Welcome to the blog
    feature_image: "/assets/default-social-image.png"

# 6. Jekyll sitemap settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
title: "Human-Ready Future" # Site name or title, also used in jekyll-seo-tag
# logo: "/assets/logos/logo.svg"  Site logo, also used in jekyll-seo-tag
url: "https://humanreadyfuture.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/110101/blog_humanreadyfuture"
email: "110101lab@googlemail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
service_worker: false # Will turn off the service worker if set to false

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/favicons/logo@16px.png'
  32: '/assets/favicons/logo@32px.png'
  96: '/assets/favicons/logo@96px.png'
  120: '/assets/favicons/logo@120px.png'
  144: '/assets/favicons/logo@144px.png'
  180: '/assets/favicons/logo@180px.png'
  512: '/assets/favicons/logo@512px.png'
  1024: '/assets/favicons/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Über
  url: /about/
- title: Themen
  url: /categories/
- title: Suche
  url: /search/

navigation_footer:
- title: Crafted with &#9829; in Munich | Europe
  copyright: 110101 Lab - Malte K

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/110101lab
  LinkedIn: https://www.linkedin.com/in/malte-kassen/
  GitHub: https://github.com/110101

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#666666"
  facebook: "#666666"
  GitHub: "#666666"
  LinkedIn: "#666666"
  Email: "#666666"
