# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- .jekyll-cache
- .gitignore
- .DS_Store

# 2. Installed Gems
plugins:
# - jekyll-sitemap
# - jekyll-paginate-v2
- jekyll-paginate-v2
#- jekyll-seo-tag
#- jekyll-feed
#- jekyll-commonmark

# 3. Gem settings
pagination:
  enabled: true
  per_page: 4
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
jekyll-mentions: https://twitter.com
twitter:
  username: 110101lab
author: Malte K
social:
  name: Malte K
  links:
    - https://twitter.com/110101lab
    - https://github.com/110101
markdown: kramdown # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more -->
timezone: Europe/London
highlighter: rouge
title: "Human-Ready Future"
url: "https://humanreadyfuture.com"
baseurl: ""

# 5. Collections
collections:
  posts:
    title: Human-Ready Future
    description: thoughts about tech & society
    output: true
    feature_text: |
      Welcome to Human-Ready Future
    feature_image: "/assets/default-social-image.png"

# 6. Jekyll sitemap settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

repo: "https://github.com/110101/blog_humanreadyfuture"
email: "110101lab@googlemail.com"

favicons: # size: path
  16: '/assets/favicons/logo@16px.png'
  32: '/assets/favicons/logo@32px.png'
  96: '/assets/favicons/logo@96px.png'
  120: '/assets/favicons/logo@120px.png'
  144: '/assets/favicons/logo@144px.png'
  180: '/assets/favicons/logo@180px.png'
  512: '/assets/favicons/logo@512px.png'
  1024: '/assets/favicons/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: About
  url: /about/
- title: Thoughts
  url: /categories/
- title: Search
  url: /search/

navigation_footer:
- title: Crafted with &#9829; in Munich | Europe
  copyright: 110101 Lab - Malte K.

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/110101lab
  LinkedIn: https://www.linkedin.com/in/malte-kassen/
  GitHub: https://github.com/110101

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: true
  LinkedIn: true
  Email: true
