name: Jekyll site CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && apk add nodejs jpegoptim jpeg pngquant gifsicle && bundle update && bundle exec && jekyll build"
    - uses: chrislennon/action-aws-cli@v1.1
    - name: push site to s3
      run: aws s3 sync _site/ s3://${{ secrets.S3_BUCKET }} --delete --metadata-directive REPLACE  --cache-control max-age=60,public  && aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_ID }} --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
